const phonemes = {
  'Long oo': {
    'JollyPhonics': 5,
    'grapheme': {
      'main': 'oo',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'oo',
    'type': 2,
    'vowel': true,
  },
  'a': {
    'JollyPhonics': 1,
    'grapheme': {
      'main': 'a',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 1,
    'phoneme': 'a',
    'type': 1,
    'vowel': true,
  },
  'ae': {
    'JollyPhonics': 4,
    'grapheme': {
      'main': 'ae',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ae',
    'type': 2,
    'vowel': true,
  },
  'air': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'air',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'air',
    'type': 3,
    'vowel': true,
  },
  'ar': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'ar',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ar',
    'type': 2,
    'vowel': true,
  },
  'b': {
    'JollyPhonics': 3,
    'grapheme': {
      'main': 'b',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 5,
    'phoneme': 'b',
    'type': 1,
    'vowel': false,
  },
  'ch': {
    'JollyPhonics': 6,
    'grapheme': {
      'main': 'ch',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ch',
    'type': 2,
    'vowel': false,
  },
  'd': {
    'JollyPhonics': 2,
    'grapheme': {
      'alt1': 'dd',
      'alt2': 'ed',
      'main': 'd',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 2,
    'phoneme': 'd',
    'type': 1,
    'vowel': false,
  },
  'e': {
    'JollyPhonics': 2,
    'grapheme': {
      'main': 'e',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 4,
    'phoneme': 'e',
    'type': 1,
    'vowel': true,
  },
  'ear': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'ear',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ear',
    'type': 3,
    'vowel': true,
  },
  'ee': {
    'JollyPhonics': 4,
    'grapheme': {
      'main': 'ee',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ee',
    'type': 2,
    'vowel': true,
  },
  'er': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'er',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'er',
    'type': 2,
    'vowel': true,
  },
  'f': {
    'JollyPhonics': 3,
    'grapheme': {
      'main': 'f',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 5,
    'phoneme': 'f',
    'type': 1,
    'vowel': false,
  },
  'g': {
    'JollyPhonics': 3,
    'grapheme': {
      'main': 'g',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 3,
    'phoneme': 'g',
    'type': 1,
    'vowel': false,
  },
  'h': {
    'JollyPhonics': 2,
    'grapheme': {
      'main': 'h',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 5,
    'phoneme': 'h',
    'type': 1,
    'vowel': false,
  },
  'i': {
    'JollyPhonics': 1,
    'grapheme': {
      'main': 'i',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 2,
    'phoneme': 'i',
    'type': 1,
    'vowel': true,
  },
  'igh': {
    'JollyPhonics': 4,
    'grapheme': {
      'main': 'igh',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'igh',
    'type': 2,
    'vowel': true,
  },
  'j': {
    'JollyPhonics': 4,
    'grapheme': {
      'main': 'j',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 6,
    'phoneme': 'j',
    'type': 1,
    'vowel': false,
  },
  'k': {
    'JollyPhonics': 2,
    'grapheme': {
      'main': 'k',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 3,
    'phoneme': 'k',
    'type': 1,
    'vowel': false,
  },
  'ks': {
    'JollyPhonics': 6,
    'grapheme': {
      'main': 'ks',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ks',
    'type': 1,
    'vowel': false,
  },
  'kw': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'kw',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'kw',
    'type': 2,
    'vowel': false,
  },
  'l': {
    'JollyPhonics': 3,
    'grapheme': {
      'main': 'l',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 5,
    'phoneme': 'l',
    'type': 1,
    'vowel': false,
  },
  'long th': {
    'JollyPhonics': 6,
    'grapheme': {
      'main': 'th',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'th',
    'type': 2,
    'vowel': false,
  },
  'm': {
    'JollyPhonics': 2,
    'grapheme': {
      'alt1': 'mm',
      'alt2': 'mb',
      'alt3': 'mn',
      'alt4': 'lm',
      'main': 'm',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 2,
    'phoneme': 'm',
    'type': 1,
    'vowel': false,
  },
  'n': {
    'JollyPhonics': 1,
    'grapheme': {
      'alt1': 'nn',
      'alt2': 'kn',
      'alt3': 'gn',
      'alt4': 'pn',
      'main': 'n',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 2,
    'phoneme': 'n',
    'type': 1,
    'vowel': false,
  },
  'ng': {
    'JollyPhonics': 5,
    'grapheme': {
      'main': 'ng',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ng',
    'type': 2,
    'vowel': false,
  },
  'o': {
    'JollyPhonics': 3,
    'grapheme': {
      'main': 'o',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 3,
    'phoneme': 'o',
    'type': 1,
    'vowel': true,
  },
  'oa': {
    'JollyPhonics': 4,
    'grapheme': {
      'main': 'oa',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'oa',
    'type': 2,
    'vowel': true,
  },
  'oi': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'oi',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'oi',
    'type': 2,
    'vowel': true,
  },
  'oo': {
    'JollyPhonics': 5,
    'grapheme': {
      'main': 'oo',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'oo',
    'type': 2,
    'vowel': true,
  },
  'or': {
    'JollyPhonics': 4,
    'grapheme': {
      'main': 'or',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'or',
    'type': 2,
    'vowel': true,
  },
  'ow': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'ow',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ow',
    'type': 2,
    'vowel': true,
  },
  'p': {
    'JollyPhonics': 1,
    'grapheme': {
      'alt1': 'pp',
      'main': 'p',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 1,
    'phoneme': 'p',
    'type': 1,
    'vowel': false,
  },
  'r': {
    'JollyPhonics': 2,
    'grapheme': {
      'main': 'r',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 4,
    'phoneme': 'r',
    'type': 1,
    'vowel': false,
  },
  's': {
    'JollyPhonics': 1,
    'grapheme': {
      'alt1': 'ss',
      'alt2': 'c',
      'alt3': 'sc',
      'alt4': 'ps',
      'alt5': 'st',
      'alt6': 'ce',
      'alt7': 'se',
      'main': 's',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 1,
    'phoneme': 's',
    'type': 1,
    'vowel': false,
  },
  'sh': {
    'JollyPhonics': 6,
    'grapheme': {
      'main': 'sh',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'sh',
    'type': 2,
    'vowel': false,
  },
  't': {
    'JollyPhonics': 1,
    'grapheme': {
      'alt1': 'tt',
      'alt2': 'th',
      'alt3': 'ed',
      'main': 't',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 1,
    'phoneme': 't',
    'type': 1,
    'vowel': false,
  },
  'th': {
    'JollyPhonics': 6,
    'grapheme': {
      'main': 'th',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'th',
    'type': 2,
    'vowel': false,
  },
  'u': {
    'JollyPhonics': 3,
    'grapheme': {
      'main': 'u',
    },
    'lettersAndSoundsPhases': 2,
    'lettersAndSoundsSets': 4,
    'phoneme': 'u',
    'type': 1,
    'vowel': true,
  },
  'ue': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'ue',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ue',
    'type': 2,
    'vowel': true,
  },
  'ur': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'ur',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ur',
    'type': 2,
    'vowel': true,
  },
  'ure': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'ure',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'ure',
    'type': 3,
    'vowel': false,
  },
  'v': {
    'JollyPhonics': 5,
    'grapheme': {
      'main': 'v',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 6,
    'phoneme': 'v',
    'type': 1,
    'vowel': false,
  },
  'w': {
    'JollyPhonics': 5,
    'grapheme': {
      'main': 'w',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 6,
    'phoneme': 'w',
    'type': 1,
    'vowel': false,
  },
  'y': {
    'JollyPhonics': 6,
    'grapheme': {
      'main': 'y',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'y',
    'type': 1,
    'vowel': false,
  },
  'z': {
    'JollyPhonics': 5,
    'grapheme': {
      'main': 'z',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'z',
    'type': 1,
    'vowel': false,
  },
  'zh': {
    'JollyPhonics': 7,
    'grapheme': {
      'main': 'zh',
    },
    'lettersAndSoundsPhases': 3,
    'lettersAndSoundsSets': 7,
    'phoneme': 'zh',
    'type': 2,
    'vowel': false,
  },
};
export {phonemes};
